# version of docker
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
# service represent container
services:
  react-app:
    build:
      # either a path to a directory containing a Dockerfile, or a url to a git repository.
      context: .
      dockerfile: Dockerfile.prod
    # port mapping
    ports:
      - '8080:80'
    # no bind mount
    # environment variables
    environment:
      - REACT_APP_NAME=brandonwie-prod
