# version of docker
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
# service represent container
services:
  react-app:
    build:
      # either a path to a directory containing a Dockerfile, or a url to a git repository.
      context: .
      dockerfile: Dockerfile.dev
    # port mapping
    ports:
      - '3001:3000'
    # bind mount
    # volume mapping
    volumes:
      - ./src:/app/src:ro
    env_file:
      - .env.dev
